# app/services/finance/setup_service.py
"""
Serviço de configuração e setup do banco de dados.

Este módulo contém funções para:
- Limpeza de sessão do bot
- Criação inicial do schema do banco
- População de categorias globais
- Setup de dados de usuário
- Migrações de schema (adicionar novas tabelas/colunas)
"""

from ._database import text, Connection, db_engine
from typing import Optional


def clear_bot_session():
    """ Limpa a sessão do bot no banco de dados. """
    if not db_engine: 
        raise Exception("Banco de dados não configurado")
        
    sql_clear = text("DELETE FROM baileys_auth WHERE session_id = 'baileys_session';")
    try:
        with db_engine.connect() as conn:
            conn.begin()
            result = conn.execute(sql_clear)
            conn.commit()
            return result.rowcount
    except Exception as e:
        print(f"[SERVICE-FIN] Erro ao limpar sessão: {e}")
        # Tenta rollback
        try: 
            with db_engine.connect() as conn: 
                conn.rollback()
        except: pass
        raise e # Re-levanta a exceção para o controller tratar

def setup_database_schema():
    """ Executa o DDL (script de criação de tabelas). """
    if not db_engine: 
        raise Exception("Banco de dados não configurado")
        
    # (DDL v12 completo, movido do app.py)
    sql_script_ddl = text("""
    DROP TABLE IF EXISTS PoteSubCategorias CASCADE; DROP TABLE IF EXISTS baileys_auth CASCADE; DROP TABLE IF EXISTS PotesDeGastos CASCADE; DROP TABLE IF EXISTS Agendamentos CASCADE; DROP TABLE IF EXISTS Transacoes CASCADE; DROP TABLE IF EXISTS Faturas CASCADE; DROP TABLE IF EXISTS Contas CASCADE; DROP TABLE IF EXISTS SubCategoria CASCADE; DROP TABLE IF EXISTS MacroCategoria CASCADE; DROP TABLE IF EXISTS GrupoCategoria CASCADE; DROP TABLE IF EXISTS Usuarios CASCADE; DROP TABLE IF EXISTS wwebjs_auth_sessions;
    CREATE TABLE Usuarios ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(255) NOT NULL, numero_whatsapp VARCHAR(50) NOT NULL UNIQUE, api_key_automate VARCHAR(100) NULL UNIQUE, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP );
    CREATE TABLE GrupoCategoria ( id SERIAL PRIMARY KEY, nome_grupo VARCHAR(100) NOT NULL UNIQUE );
    CREATE TABLE MacroCategoria ( id SERIAL PRIMARY KEY, grupo_id INT NOT NULL REFERENCES GrupoCategoria(id) ON DELETE RESTRICT, usuario_id INT REFERENCES Usuarios(id) ON DELETE CASCADE, nome_macro VARCHAR(255) NOT NULL, ordem_macro INT );
    CREATE TABLE SubCategoria ( id SERIAL PRIMARY KEY, macro_id INT NOT NULL REFERENCES MacroCategoria(id) ON DELETE CASCADE, usuario_id INT REFERENCES Usuarios(id) ON DELETE CASCADE, nome_sub VARCHAR(255) NOT NULL, UNIQUE(macro_id, nome_sub, usuario_id) );
    CREATE TABLE Contas ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE, nome_conta VARCHAR(100) NOT NULL, tipo_conta VARCHAR(50) NOT NULL CHECK (tipo_conta IN ('Conta Corrente', 'Conta Poupança', 'Investimento', 'Cartão de Crédito', 'Dinheiro', 'Outro')), saldo_inicial NUMERIC(15, 2) NOT NULL DEFAULT 0.00, dia_vencimento INT NULL CHECK (dia_vencimento >= 1 AND dia_vencimento <= 31), dia_fechamento INT NULL CHECK (dia_fechamento >= 1 AND dia_fechamento <= 31), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, UNIQUE(usuario_id, nome_conta), CONSTRAINT chk_cartao_credito CHECK ( (tipo_conta = 'Cartão de Crédito') OR (dia_vencimento IS NULL AND dia_fechamento IS NULL) ) );
    CREATE TABLE Faturas ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conta_id INT NOT NULL REFERENCES Contas(id) ON DELETE CASCADE, data_vencimento DATE NOT NULL, data_fechamento DATE NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'Aberta' CHECK (status IN ('Aberta', 'Fechada', 'Paga')), UNIQUE(conta_id, data_vencimento) );
    CREATE TABLE Transacoes ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE, conta_id INT NOT NULL REFERENCES Contas(id) ON DELETE RESTRICT, subcategoria_id INT NOT NULL REFERENCES SubCategoria(id) ON DELETE RESTRICT, fatura_id INT NULL REFERENCES Faturas(id) ON DELETE SET NULL, transferencia_par_id INT NULL REFERENCES Transacoes(id) ON DELETE SET NULL, descricao VARCHAR(255) NOT NULL, valor NUMERIC(15, 2) NOT NULL, data_transacao DATE NOT NULL DEFAULT CURRENT_DATE, tipo_transacao VARCHAR(20) NOT NULL CHECK (tipo_transacao IN ('Renda', 'Despesa', 'Transferência', 'Pagamento Fatura')), consolidada BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP );
    CREATE TABLE Agendamentos ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE, conta_id INT NOT NULL REFERENCES Contas(id) ON DELETE CASCADE, subcategoria_id INT NOT NULL REFERENCES SubCategoria(id) ON DELETE RESTRICT, descricao VARCHAR(255) NOT NULL, valor_previsto NUMERIC(15, 2), tipo_agendamento VARCHAR(20) NOT NULL CHECK (tipo_agendamento IN ('FIXO', 'PARCELADO', 'LEMBRETE_VARIAVEL')), periodicidade VARCHAR(20) NOT NULL CHECK (periodicidade IN ('DIARIA', 'SEMANAL', 'QUINZENAL', 'MENSAL', 'ANUAL')), data_inicio DATE NOT NULL, dia_execucao INT NOT NULL CHECK (dia_execucao >= 1 AND dia_execucao <= 31), total_parcelas INT, parcelas_executadas INT DEFAULT 0, notificar_antes_dias INT DEFAULT 3, ativo BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, CONSTRAINT chk_parcelado CHECK ( (tipo_agendamento = 'PARCELADO') OR (total_parcelas IS NULL AND parcelas_executadas = 0) ) );
    CREATE TABLE PotesDeGastos ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE, nome_pote VARCHAR(100) NOT NULL, valor_limite NUMERIC(15, 2) NOT NULL, periodicidade VARCHAR(20) NOT NULL DEFAULT 'MENSAL' CHECK (periodicidade IN ('SEMANAL', 'QUINZENAL', 'MENSAL', 'ANUAL')), data_inicio DATE NOT NULL DEFAULT CURRENT_DATE, ativo BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(usuario_id, nome_pote) );
    CREATE TABLE PoteSubCategorias ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, pote_id INT NOT NULL REFERENCES PotesDeGastos(id) ON DELETE CASCADE, subcategoria_id INT NOT NULL REFERENCES SubCategoria(id) ON DELETE CASCADE, UNIQUE(pote_id, subcategoria_id) );
    CREATE TABLE IF NOT EXISTS baileys_auth (session_id VARCHAR(100), data_key VARCHAR(100), data_value TEXT, PRIMARY KEY (session_id, data_key));
    CREATE INDEX IF NOT EXISTS idx_usuarios_api_key_automate ON Usuarios(api_key_automate); CREATE INDEX IF NOT EXISTS idx_macro_usuario_id ON MacroCategoria(usuario_id); CREATE INDEX IF NOT EXISTS idx_sub_usuario_id ON SubCategoria(usuario_id); CREATE INDEX IF NOT EXISTS idx_contas_usuario_id ON Contas(usuario_id); CREATE INDEX IF NOT EXISTS idx_faturas_conta_id ON Faturas(conta_id); CREATE INDEX IF NOT EXISTS idx_transacoes_usuario_id ON Transacoes(usuario_id); CREATE INDEX IF NOT EXISTS idx_transacoes_fatura_id ON Transacoes(fatura_id); CREATE INDEX IF NOT EXISTS idx_transacoes_transfer_par_id ON Transacoes(transferencia_par_id); CREATE INDEX IF NOT EXISTS idx_agendamentos_usuario_id ON Agendamentos(usuario_id); CREATE INDEX IF NOT EXISTS idx_potes_usuario_id ON PotesDeGastos(usuario_id); CREATE INDEX IF NOT EXISTS idx_pote_subcat_pote_id ON PoteSubCategorias(pote_id); CREATE INDEX IF NOT EXISTS idx_pote_subcat_subcat_id ON PoteSubCategorias(subcategoria_id);
    """)
    
    try:
        with db_engine.connect() as conn:
            conn.execute(sql_script_ddl) 
            conn.commit() 
    except Exception as e:
        print(f"Erro ao criar estrutura do banco: {e}")
        try: 
            with db_engine.connect() as conn: 
                conn.rollback()
        except: pass
        raise e

def populate_global_categories():
    """ Executa o DML (script de inserção de categorias globais). """
    if not db_engine: 
        raise Exception("Banco de dados não configurado")

    # (DML global, movido do app.py)
    sql_populate_dml = text("""
    DELETE FROM SubCategoria WHERE usuario_id IS NULL; DELETE FROM MacroCategoria WHERE usuario_id IS NULL; DELETE FROM GrupoCategoria;
    INSERT INTO GrupoCategoria (nome_grupo) VALUES ('Renda'), ('Despesa Essencial'), ('Meta Financeira'), ('Despesa Discricionária'), ('Geral');
    INSERT INTO MacroCategoria (grupo_id, nome_macro, ordem_macro) VALUES
        ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Renda'), 'Renda Principal', 1), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Renda'), 'Renda Extra e Passiva', 2), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Renda'), 'Investimentos e Reembolsos', 3), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Renda'), 'Outras Entradas', 4),
        ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Moradia e Contas', 1), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Alimentação Essencial', 2), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Saúde e Bem-Estar Básico', 3), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Educação Essencial', 4), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Transporte Essencial', 5),
        ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Meta Financeira'), 'Construção de Riqueza', 1), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Meta Financeira'), 'Gerenciamento de Dívidas', 2), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Meta Financeira'), 'Educação de Alto Custo', 3),
        ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Discricionária'), 'Lazer e Entretenimento', 1), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Discricionária'), 'Assinaturas e Serviços', 2), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Discricionária'), 'Cuidados Pessoais', 3), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Discricionária'), 'Compras Pessoais', 4),
        ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Geral'), 'Despesas Gerais', NULL), ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Geral'), 'Receitas Gerais', NULL);
    INSERT INTO SubCategoria (macro_id, nome_sub) VALUES
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Principal' AND usuario_id IS NULL), 'Salário Fixo / Pró-labore'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Principal' AND usuario_id IS NULL), 'Remuneração Variável / Comissões'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Extra e Passiva' AND usuario_id IS NULL), 'Aluguéis Recebidos'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Extra e Passiva' AND usuario_id IS NULL), 'Freelances / Projetos Avulsos'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Investimentos e Reembolsos' AND usuario_id IS NULL), 'Dividendos / Juros (Rendimentos)'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Investimentos e Reembolsos' AND usuario_id IS NULL), 'Restituições / Reembolsos'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Outras Entradas' AND usuario_id IS NULL), 'Presentes em Dinheiro / Doações'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Outras Entradas' AND usuario_id IS NULL), 'Venda de Bens (Pontual)'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Aluguel / Financiamento'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Condomínio / IPTU / Taxas'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Eletricidade / Água / Gás'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Internet / Telefone Fixo'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Manutenção da Casa'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Alimentação Essencial' AND usuario_id IS NULL), 'Supermercado / Mercearia'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Alimentação Essencial' AND usuario_id IS NULL), 'Feira / Hortifrúti'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Alimentação Essencial' AND usuario_id IS NULL), 'Suplementos e Itens Básicos'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Saúde e Bem-Estar Básico' AND usuario_id IS NULL), 'Plano de Saúde / Convênio'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Saúde e Bem-Estar Básico' AND usuario_id IS NULL), 'Medicamentos de Uso Contínuo'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Saúde e Bem-Estar Básico' AND usuario_id IS NULL), 'Consultas e Exames (não cobertos)'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Educação Essencial' AND usuario_id IS NULL), 'Mensalidades Escolares / Faculdade'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Educação Essencial' AND usuario_id IS NULL), 'Material Didático e Livros'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Transporte Essencial' AND usuario_id IS NULL), 'Combustível / Recarga (Carro/Moto)'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Transporte Essencial' AND usuario_id IS NULL), 'Transporte Público (Bilhetes/Passe)'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Transporte Essencial' AND usuario_id IS NULL), 'Aplicativos de Transporte (Necessidade)'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Transporte Essencial' AND usuario_id IS NULL), 'IPVA / Seguro do Veículo'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Construção de Riqueza' AND usuario_id IS NULL), 'Aporte à Reserva de Emergência'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Construção de Riqueza' AND usuario_id IS NULL), 'Investimentos para Aposentadoria'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Construção de Riqueza' AND usuario_id IS NULL), 'Investimentos de Curto Prazo'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Gerenciamento de Dívidas' AND usuario_id IS NULL), 'Quitação de Empréstimos (Principal)'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Gerenciamento de Dívidas' AND usuario_id IS NULL), 'Juros e Multas (Dívidas)'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Educação de Alto Custo' AND usuario_id IS NULL), 'Pós-graduação, Intercâmbio'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Lazer e Entretenimento' AND usuario_id IS NULL), 'Restaurantes, Bares e Delivery'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Lazer e Entretenimento' AND usuario_id IS NULL), 'Passeios e Eventos Culturais'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Lazer e Entretenimento' AND usuario_id IS NULL), 'Viagens e Hospedagem'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Assinaturas e Serviços' AND usuario_id IS NULL), 'Streaming (Netflix, Spotify, etc.)'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Assinaturas e Serviços' AND usuario_id IS NULL), 'Softwares / Apps Pagos'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Assinaturas e Serviços' AND usuario_id IS NULL), 'Academia / Clube'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Cuidados Pessoais' AND usuario_id IS NULL), 'Salão de Beleza / Barbearia'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Cuidados Pessoais' AND usuario_id IS NULL), 'Cosméticos e Higiene (não básica)'),
        ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Compras Pessoais' AND usuario_id IS NULL), 'Roupas, Calçados e Acessórios'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Compras Pessoais' AND usuario_id IS NULL), 'Eletrônicos e Gadgets'), ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Compras Pessoais' AND usuario_id IS NULL), 'Presentes (Aniversários, Datas)');
    INSERT INTO SubCategoria (macro_id, nome_sub) SELECT id, 'Outros' FROM MacroCategoria WHERE usuario_id IS NULL;
    """)
    
    try:
        with db_engine.connect() as conn:
            conn.begin()
            conn.execute(sql_populate_dml) 
            conn.commit()
    except Exception as e:
        print(f"Erro ao inserir templates globais: {e}")
        try: 
            with db_engine.connect() as conn: 
                conn.rollback()
        except: pass
        raise e

def setup_user_data(numero_whatsapp, dia_venc_cartao, dia_fech_cartao):
    """ Insere/Atualiza os dados de um usuário e suas contas padrão. """
    if not db_engine: 
        raise Exception("Banco de dados não configurado")
        
    nova_api_key = secrets.token_hex(20) 

    sql_user = text(f"""
    INSERT INTO Usuarios (nome, numero_whatsapp, api_key_automate) 
    VALUES ('Rafael', :num_wpp, :api_key) 
    ON CONFLICT (numero_whatsapp) 
    DO UPDATE SET 
        nome = EXCLUDED.nome,
        api_key_automate = EXCLUDED.api_key_automate 
    RETURNING id, api_key_automate;
    """)
    
    try:
        user_id = None
        api_key_retornada = None
        
        with db_engine.connect() as conn:
            conn.begin()
            result = conn.execute(sql_user, {
                "num_wpp": numero_whatsapp,
                "api_key": nova_api_key
            })
            user_data = result.fetchone() 
            
            if user_data:
                user_id = user_data[0]
                api_key_retornada = user_data[1]
            else:
                # Se o ON CONFLICT não retornou (pode acontecer em algumas configs de PG)
                sql_find = text("SELECT id, api_key_automate FROM Usuarios WHERE numero_whatsapp = :num")
                user_data = conn.execute(sql_find, {"num": numero_whatsapp}).fetchone()
                user_id = user_data[0]
                api_key_retornada = user_data[1]
            
            sql_accounts_com_id = text(f"""
                INSERT INTO Contas (usuario_id, nome_conta, tipo_conta, dia_vencimento, dia_fechamento) VALUES 
                    (:uid, 'Banco Inter', 'Conta Corrente', NULL, NULL),         
                    (:uid, 'Cartão Inter', 'Cartão de Crédito', :dia_venc, :dia_fech),
                    (:uid, 'Nubank', 'Conta Corrente', NULL, NULL),             
                    (:uid, 'Carteira', 'Dinheiro', NULL, NULL)
                ON CONFLICT (usuario_id, nome_conta) DO UPDATE SET
                    tipo_conta = EXCLUDED.tipo_conta,
                    dia_vencimento = EXCLUDED.dia_vencimento,
                    dia_fechamento = EXCLUDED.dia_fechamento; 
            """)
            
            conn.execute(sql_accounts_com_id, {
                "uid": user_id,
                "dia_venc": dia_venc_cartao,
                "dia_fech": dia_fech_cartao
            }) 
            conn.commit()
        
        return user_id, api_key_retornada

    except Exception as e:
        print(f"Erro ao inserir dados do usuário: {e}")
        try: 
            with db_engine.connect() as conn: 
                conn.rollback()
        except: pass
        raise e

def add_google_calendar_tokens_table():
    """Adiciona tabela para armazenar tokens OAuth2 do Google Calendar"""
    if not db_engine:
        raise Exception("Banco não configurado")

    sql = text("""
        CREATE TABLE IF NOT EXISTS GoogleCalendarTokens (
            id SERIAL PRIMARY KEY,
            usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
            access_token TEXT NOT NULL,
            refresh_token TEXT,
            token_expiry TIMESTAMP WITH TIME ZONE,
            scopes TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(usuario_id)
        );

        CREATE INDEX IF NOT EXISTS idx_calendar_tokens_usuario
        ON GoogleCalendarTokens(usuario_id);
    """)

    try:
        with db_engine.connect() as conn:
            conn.begin()
            conn.execute(sql)
            conn.commit()
            print("[DB] ✅ Tabela GoogleCalendarTokens criada/verificada")
    except Exception as e:
        print(f"[DB] Erro ao criar tabela: {e}")
        raise


def add_nightly_checkin_config_columns():
    """
    Adiciona colunas de check-in noturno na tabela NotificationConfigs.
    Função idempotente - pode ser executada múltiplas vezes sem erros.
    """
    if not db_engine:
        raise Exception("Banco não configurado")

    sql = text("""
        -- Adicionar colunas
        ALTER TABLE NotificationConfigs
        ADD COLUMN IF NOT EXISTS checkin_noturno_ativo BOOLEAN NOT NULL DEFAULT TRUE,
        ADD COLUMN IF NOT EXISTS checkin_noturno_hora TIME NOT NULL DEFAULT '20:00:00';

        -- Adicionar constraint (usando DO para evitar erro se já existe)
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'chk_checkin_hora'
            ) THEN
                ALTER TABLE NotificationConfigs
                ADD CONSTRAINT chk_checkin_hora CHECK (
                    checkin_noturno_hora >= '18:00:00'::TIME
                    AND checkin_noturno_hora <= '23:00:00'::TIME
                );
            END IF;
        END $$;

        -- Adicionar comentários
        COMMENT ON COLUMN NotificationConfigs.checkin_noturno_ativo IS
        'Se TRUE, envia check-in noturno com contas pendentes (D-0 até D-7)';

        COMMENT ON COLUMN NotificationConfigs.checkin_noturno_hora IS
        'Horário para envio do check-in noturno (18:00-23:00)';
    """)

    try:
        with db_engine.connect() as conn:
            with conn.begin():
                conn.execute(sql)
            print("[MIGRATION] ✅ Colunas de check-in noturno adicionadas com sucesso")
            return True
    except Exception as e:
        print(f"[MIGRATION] ❌ Erro ao adicionar colunas: {e}")
        import traceback
        traceback.print_exc()
        return False


def criar_tabelas_chaves_api():
    """
    Cria tabelas para sistema de chaves de API por usuário (SaaS).

    NOVIDADES:
    - ChavesApiUsuario: Armazena chaves do usuário (criptografadas)
    - PreferenciasChaveApi: Escolha explícita (chave própria ou sistema)
    - LogAcessoChaveApi: Auditoria de segurança
    - RastreamentoUsoApi: Tracking para billing
    - ConsentimentoUsuario: LGPD compliance
    - Planos + AssinaturasUsuario: Sistema de planos (Bronze, Prata, Ouro)

    Função idempotente - pode ser executada múltiplas vezes.
    """
    if not db_engine:
        raise Exception("Banco não configurado")

    sql = text("""
        -- Tabela 1: Armazenamento de chaves do usuário
        CREATE TABLE IF NOT EXISTS ChavesApiUsuario (
            id SERIAL PRIMARY KEY,
            usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
            provedor VARCHAR(50) NOT NULL,
            chave_api_criptografada TEXT NOT NULL,
            ativo BOOLEAN DEFAULT TRUE,
            criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            ultimo_uso_em TIMESTAMP WITH TIME ZONE,
            consentimento_dado BOOLEAN DEFAULT TRUE,
            consentimento_data TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(usuario_id, provedor)
        );

        CREATE INDEX IF NOT EXISTS idx_chaves_api_usuario ON ChavesApiUsuario(usuario_id);
        CREATE INDEX IF NOT EXISTS idx_chaves_api_ativo
            ON ChavesApiUsuario(usuario_id, provedor) WHERE ativo = TRUE;

        -- Tabela 2: Preferências (escolha explícita do usuário)
        CREATE TABLE IF NOT EXISTS PreferenciasChaveApi (
            id SERIAL PRIMARY KEY,
            usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
            provedor VARCHAR(50) NOT NULL,
            usar_chave_propria BOOLEAN NOT NULL DEFAULT FALSE,
            criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(usuario_id, provedor)
        );

        CREATE INDEX IF NOT EXISTS idx_preferencias_usuario ON PreferenciasChaveApi(usuario_id);

        COMMENT ON COLUMN PreferenciasChaveApi.usar_chave_propria IS
        'FALSE = usa chave do sistema (PAGA), TRUE = usa chave própria (GRÁTIS)';

        -- Tabela 3: Logs de acesso (auditoria)
        CREATE TABLE IF NOT EXISTS LogAcessoChaveApi (
            id SERIAL PRIMARY KEY,
            usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
            provedor VARCHAR(50) NOT NULL,
            tipo_chave VARCHAR(20) NOT NULL,
            operacao VARCHAR(50) NOT NULL,
            sucesso BOOLEAN NOT NULL,
            mensagem_erro TEXT,
            timestamp_acesso TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            endereco_ip VARCHAR(45),
            criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_log_acesso_usuario
            ON LogAcessoChaveApi(usuario_id, timestamp_acesso DESC);
        CREATE INDEX IF NOT EXISTS idx_log_acesso_provedor
            ON LogAcessoChaveApi(provedor, timestamp_acesso DESC);

        -- Tabela 4: Rastreamento de uso (billing)
        CREATE TABLE IF NOT EXISTS RastreamentoUsoApi (
            id SERIAL PRIMARY KEY,
            usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
            provedor VARCHAR(50) NOT NULL,
            tipo_chave VARCHAR(20) NOT NULL,
            quantidade_chamadas INT DEFAULT 0,
            mes_ano VARCHAR(7) NOT NULL,
            valor_cobrado NUMERIC(10, 2) DEFAULT 0.00,
            criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(usuario_id, provedor, tipo_chave, mes_ano)
        );

        CREATE INDEX IF NOT EXISTS idx_rastreamento_mes ON RastreamentoUsoApi(mes_ano, provedor);
        CREATE INDEX IF NOT EXISTS idx_rastreamento_usuario ON RastreamentoUsoApi(usuario_id, mes_ano DESC);

        -- Tabela 5: Consentimentos LGPD
        CREATE TABLE IF NOT EXISTS ConsentimentoUsuario (
            id SERIAL PRIMARY KEY,
            usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
            tipo_consentimento VARCHAR(50) NOT NULL,
            versao_consentimento VARCHAR(20) NOT NULL,
            consentimento_dado BOOLEAN NOT NULL,
            data_consentimento TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            ip_consentimento VARCHAR(45),
            texto_consentimento TEXT,
            revogado_em TIMESTAMP WITH TIME ZONE,
            UNIQUE(usuario_id, tipo_consentimento, versao_consentimento)
        );

        CREATE INDEX IF NOT EXISTS idx_consentimento_ativo
            ON ConsentimentoUsuario(usuario_id, tipo_consentimento)
            WHERE consentimento_dado = TRUE AND revogado_em IS NULL;

        -- Tabela 6: Planos (sistema de assinaturas)
        CREATE TABLE IF NOT EXISTS Planos (
            id SERIAL PRIMARY KEY,
            nome_plano VARCHAR(50) NOT NULL UNIQUE,
            descricao TEXT,
            preco_mensal NUMERIC(10, 2) NOT NULL,
            limite_gemini INT,
            limite_weather INT,
            limite_openroute INT,
            custo_por_chamada_gemini NUMERIC(10, 4) DEFAULT 0.01,
            custo_por_chamada_weather NUMERIC(10, 4) DEFAULT 0.005,
            custo_por_chamada_openroute NUMERIC(10, 4) DEFAULT 0.02,
            permite_chaves_proprias BOOLEAN DEFAULT TRUE,
            ativo BOOLEAN DEFAULT TRUE,
            criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        -- Inserir planos padrão (idempotente)
        INSERT INTO Planos (nome_plano, descricao, preco_mensal, limite_gemini, limite_weather, limite_openroute)
        VALUES
            ('Bronze', 'Plano básico gratuito', 0.00, 100, 50, 10),
            ('Prata', 'Plano intermediário', 29.90, 500, 200, 50),
            ('Ouro', 'Plano premium ilimitado', 79.90, NULL, NULL, NULL)
        ON CONFLICT (nome_plano) DO NOTHING;

        -- Tabela 7: Assinaturas dos usuários
        CREATE TABLE IF NOT EXISTS AssinaturasUsuario (
            id SERIAL PRIMARY KEY,
            usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
            plano_id INT NOT NULL REFERENCES Planos(id) ON DELETE RESTRICT,
            data_inicio TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            data_fim TIMESTAMP WITH TIME ZONE,
            status VARCHAR(20) NOT NULL DEFAULT 'ativo',
            criado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_assinaturas_usuario ON AssinaturasUsuario(usuario_id, status);
        CREATE INDEX IF NOT EXISTS idx_assinaturas_ativas ON AssinaturasUsuario(usuario_id)
            WHERE status = 'ativo' AND (data_fim IS NULL OR data_fim > CURRENT_TIMESTAMP);
    """)

    try:
        with db_engine.connect() as conn:
            conn.begin()
            conn.execute(sql)
            conn.commit()
            print("[DB] ✅ Tabelas de chaves de API criadas com sucesso (PT-BR)")
            print("[DB] ℹ️ Tabelas criadas: ChavesApiUsuario, PreferenciasChaveApi, LogAcessoChaveApi,")
            print("[DB] ℹ️                    RastreamentoUsoApi, ConsentimentoUsuario, Planos, AssinaturasUsuario")
            return True
    except Exception as e:
        print(f"[DB] ❌ Erro ao criar tabelas: {e}")
        import traceback
        traceback.print_exc()
        return False


__all__ = [
    'clear_bot_session',
    'setup_database_schema',
    'populate_global_categories',
    'setup_user_data',
    'add_google_calendar_tokens_table',
    'add_nightly_checkin_config_columns',
    'criar_tabelas_chaves_api',
]
