#!/usr/bin/env python3
"""
Migration: Adiciona tabela EnderecosFavoritos
Data: 2025-11-27
Descrição: Cria tabela para armazenar até 3 endereços favoritos por usuário
           (casa, trabalho, outro) para cálculo de tempo de deslocamento
"""

import os
from sqlalchemy import create_engine, text

def run_migration():
    """Executa a migration para criar tabela EnderecosFavoritos"""

    # Carregar DATABASE_URL
    DATABASE_URL = os.environ.get('DATABASE_URL')
    if not DATABASE_URL:
        print("❌ ERRO: Variável DATABASE_URL não configurada")
        return False

    # Ajustar URL se necessário (postgres:// -> postgresql://)
    if DATABASE_URL.startswith("postgres://"):
        DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

    try:
        engine = create_engine(DATABASE_URL)

        with engine.connect() as conn:
            print("🔄 Iniciando migration: criar tabela EnderecosFavoritos...")

            # Verificar se a tabela já existe
            check_sql = text("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_name = 'enderecosfavoritos'
                )
            """)

            table_exists = conn.execute(check_sql).scalar()

            if table_exists:
                print("✅ Tabela 'EnderecosFavoritos' já existe. Migration não necessária.")
                return True

            # Executar migration
            trans = conn.begin()

            try:
                migration_sql = text("""
                    -- Criar tabela EnderecosFavoritos
                    CREATE TABLE EnderecosFavoritos (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
                        label VARCHAR(50) NOT NULL CHECK (label IN ('casa', 'trabalho', 'outro')),
                        endereco_completo TEXT NOT NULL,
                        latitude NUMERIC(10, 8),
                        longitude NUMERIC(11, 8),
                        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE(usuario_id, label)
                    );

                    -- Criar índice para busca por usuário
                    CREATE INDEX idx_enderecos_usuario ON EnderecosFavoritos(usuario_id);

                    -- Comentários de documentação
                    COMMENT ON TABLE EnderecosFavoritos IS 'Armazena até 3 endereços favoritos por usuário para cálculo de tempo de deslocamento';
                    COMMENT ON COLUMN EnderecosFavoritos.label IS 'Tipo de endereço: casa, trabalho ou outro';
                    COMMENT ON COLUMN EnderecosFavoritos.endereco_completo IS 'Endereço completo fornecido pelo usuário';
                    COMMENT ON COLUMN EnderecosFavoritos.latitude IS 'Latitude do endereço (cache de geocoding)';
                    COMMENT ON COLUMN EnderecosFavoritos.longitude IS 'Longitude do endereço (cache de geocoding)';
                """)

                conn.execute(migration_sql)
                trans.commit()

                print("✅ Migration executada com sucesso!")
                print("   - Tabela 'EnderecosFavoritos' criada")
                print("   - Constraint UNIQUE(usuario_id, label) adicionada")
                print("   - Índice de busca por usuário criado")
                print("   - Limite de 3 endereços por usuário garantido")

                return True

            except Exception as e:
                trans.rollback()
                raise e

    except Exception as e:
        print(f"❌ ERRO ao executar migration: {e}")
        return False

if __name__ == "__main__":
    success = run_migration()
    exit(0 if success else 1)
