import os
import json
from flask import Flask, request, jsonify
import google.generativeai as genai
from sqlalchemy import create_engine, text

# ========= 1. CONFIGURAÇÃO INICIAL E CONEXÃO =========

app = Flask(__name__)

# Carregar as "senhas" (Variáveis de Ambiente)
try:
    GEMINI_API_KEY = os.environ['GEMINI_API_KEY']
    DATABASE_URL = os.environ['DATABASE_URL']
except KeyError:
    GEMINI_API_KEY = None
    DATABASE_URL = None

# Configurar o cliente do Gemini
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel('models/gemini-flash-latest') 
else:
    model = None

# Configurar a conexão com o Banco de Dados (PostgreSQL)
if DATABASE_URL:
    if DATABASE_URL.startswith("postgres://"):
        DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
    engine = create_engine(DATABASE_URL)
else:
    engine = None


# ========= 2. ROTAS ADMINISTRATIVAS ========

@app.route('/admin/setup-database', methods=['GET'])
def setup_database():
    """
    Cria a estrutura COMPLETA do banco, incluindo as novas tabelas de categorias
    e ajustando a tabela Transacoes.
    """
    if not engine:
        return "Erro: Conexão com o banco de dados não configurada.", 500

    # Script SQL para criar TODA a estrutura
    sql_script_ddl = """
    -- Remove tipos antigos se existirem
    DROP TYPE IF EXISTS tipo_conta CASCADE;
    DROP TYPE IF EXISTS tipo_fluxo CASCADE;
    
    -- Remove tabelas antigas se existirem (na ordem correta)
    DROP TABLE IF EXISTS Transacoes CASCADE;
    DROP TABLE IF EXISTS SubCategoria CASCADE;
    DROP TABLE IF EXISTS MacroCategoria CASCADE;
    DROP TABLE IF EXISTS GrupoCategoria CASCADE;
    DROP TABLE IF EXISTS Contas CASCADE;
    DROP TABLE IF EXISTS Usuarios CASCADE;

    -- Recria tipos necessários
    CREATE TYPE tipo_conta AS ENUM ('Conta Corrente', 'Cartão de Crédito', 'Dinheiro Físico', 'Investimento');

    -- Criação das tabelas
    CREATE TABLE Usuarios (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(255) NOT NULL,
        numero_whatsapp VARCHAR(50) NOT NULL UNIQUE,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE Contas (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_usuario INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
        nome VARCHAR(255) NOT NULL,
        tipo tipo_conta NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(id_usuario, nome)
    );
    
    -- === NOVAS TABELAS DE CATEGORIA ===
    CREATE TABLE GrupoCategoria (
        id SERIAL PRIMARY KEY,
        nome_grupo VARCHAR(100) NOT NULL UNIQUE
    );

    CREATE TABLE MacroCategoria (
        id SERIAL PRIMARY KEY,
        grupo_id INT NOT NULL REFERENCES GrupoCategoria(id) ON DELETE RESTRICT,
        nome_macro VARCHAR(255) NOT NULL,
        ordem_macro INT -- Nullable, pode não ter ordem
    );

    CREATE TABLE SubCategoria (
        id SERIAL PRIMARY KEY,
        macro_id INT NOT NULL REFERENCES MacroCategoria(id) ON DELETE CASCADE,
        nome_sub VARCHAR(255) NOT NULL,
        -- Garante que não haja subcategorias repetidas dentro da mesma macro
        UNIQUE(macro_id, nome_sub) 
    );
    -- === FIM NOVAS TABELAS DE CATEGORIA ===

    CREATE TABLE Transacoes (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_conta INT NOT NULL REFERENCES Contas(id) ON DELETE CASCADE,
        
        -- AGORA LIGA COM A SUBCATEGORIA!
        id_subcategoria INT REFERENCES SubCategoria(id) ON DELETE SET NULL, 
        
        descricao VARCHAR(500) NOT NULL,
        valor NUMERIC(12, 2) NOT NULL CHECK (valor > 0),
        
        -- Precisamos saber se é Receita/Despesa na própria transação
        -- Poderia derivar do GrupoCategoria, mas deixamos explícito aqui
        tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('RECEITA', 'DESPESA')), 
        
        data TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    -- Índices
    CREATE INDEX IF NOT EXISTS idx_macro_grupo_id ON MacroCategoria(grupo_id);
    CREATE INDEX IF NOT EXISTS idx_sub_macro_id ON SubCategoria(macro_id);
    CREATE INDEX IF NOT EXISTS idx_transacoes_conta ON Transacoes(id_conta);
    CREATE INDEX IF NOT EXISTS idx_transacoes_subcategoria ON Transacoes(id_subcategoria);
    """
    
    try:
        with engine.connect() as conn:
            conn.execute(text(sql_script_ddl))
            conn.commit() 
        return "Estrutura completa do banco criada/recriada com sucesso!", 200
    except Exception as e:
        return f"Erro ao criar estrutura do banco: {e}", 500


@app.route('/admin/populate-data', methods=['GET'])
def populate_initial_data():
    """
    Insere o Usuário, Contas e TODAS as suas categorias detalhadas.
    Execute UMA VEZ após rodar /admin/setup-database.
    """
    if not engine:
        return "Erro: Conexão com o banco de dados não configurada.", 500

    # !!! IMPORTANTE: SUBSTITUIR PELO SEU NÚMERO REAL !!!
    numero_whatsapp_usuario = '553194001072' 

    # === SEU NOVO SCRIPT SQL DE POPULAÇÃO ===
    sql_populate_dml = text(f"""
    BEGIN; 

    -- Limpa dados antes de inserir (mantém estrutura)
    DELETE FROM SubCategoria;
    DELETE FROM MacroCategoria;
    DELETE FROM GrupoCategoria;
    DELETE FROM Contas;
    DELETE FROM Usuarios;
    
    -- Insere Usuário
    INSERT INTO Usuarios (nome, numero_whatsapp) VALUES ('Rafael', '{numero_whatsapp_usuario}');
    -- Assumindo ID=1

    -- Insere Contas
    INSERT INTO Contas (id_usuario, nome, tipo) VALUES 
        (1, 'Banco Inter', 'Conta Corrente'),         
        (1, 'Cartão Inter', 'Cartão de Crédito'),    
        (1, 'Nubank', 'Conta Corrente'),             
        (1, 'Carteira', 'Dinheiro Físico'); 

    -- 2.1. Inserir os Grupos Principais
    INSERT INTO GrupoCategoria (nome_grupo) VALUES
    ('Renda'),
    ('Despesa Essencial'),
    ('Meta Financeira'),
    ('Despesa Discricionária'),
    ('Geral'); -- Adicionando um grupo geral para categorias como "Outros"

    -- 2.2. Inserir as Macro Categorias
    INSERT INTO MacroCategoria (grupo_id, nome_macro, ordem_macro) VALUES
    -- Rendas (Grupo 1)
    (1, 'Renda Principal', 1), (1, 'Renda Extra e Passiva', 2), (1, 'Investimentos e Reembolsos', 3), (1, 'Outras Entradas', 4),
    -- Despesas Essenciais (Grupo 2)
    (2, 'Moradia e Contas', 1), (2, 'Alimentação Essencial', 2), (2, 'Saúde e Bem-Estar Básico', 3), (2, 'Educação Essencial', 4), (2, 'Transporte Essencial', 5),
    -- Metas Financeiras (Grupo 3)
    (3, 'Construção de Riqueza', 1), (3, 'Gerenciamento de Dívidas', 2), (3, 'Educação de Alto Custo', 3),
    -- Despesas Discricionárias (Grupo 4)
    (4, 'Lazer e Entretenimento', 1), (4, 'Assinaturas e Serviços', 2), (4, 'Cuidados Pessoais', 3), (4, 'Compras Pessoais', 4),
    -- Geral (Grupo 5)
    (5, 'Despesas Gerais', NULL), -- Macro para Despesas "Outros"
    (5, 'Receitas Gerais', NULL); -- Macro para Receitas "Outros"


    -- 2.3. Inserir as Sub Categorias
    INSERT INTO SubCategoria (macro_id, nome_sub) VALUES
    -- Rendas
    (1, 'Salário Fixo / Pró-labore'), (1, 'Remuneração Variável / Comissões'),
    (2, 'Aluguéis Recebidos'), (2, 'Freelances / Projetos Avulsos'),
    (3, 'Dividendos / Juros (Rendimentos)'), (3, 'Restituições / Reembolsos'),
    (4, 'Presentes em Dinheiro / Doações'), (4, 'Venda de Bens (Pontual)'),
    -- Despesas Essenciais
    (5, 'Aluguel / Financiamento'), (5, 'Condomínio / IPTU / Taxas'), (5, 'Eletricidade / Água / Gás'), (5, 'Internet / Telefone Fixo'), (5, 'Manutenção da Casa'),
    (6, 'Supermercado / Mercearia'), (6, 'Feira / Hortifrúti'), (6, 'Suplementos e Itens Básicos'),
    (7, 'Plano de Saúde / Convênio'), (7, 'Medicamentos de Uso Contínuo'), (7, 'Consultas e Exames (não cobertos)'),
    (8, 'Mensalidades Escolares / Faculdade'), (8, 'Material Didático e Livros'),
    (9, 'Combustível / Recarga (Carro/Moto)'), (9, 'Transporte Público (Bilhetes/Passe)'), (9, 'Aplicativos de Transporte (Necessidade)'), (9, 'IPVA / Seguro do Veículo'),
    -- Metas Financeiras
    (10, 'Aporte à Reserva de Emergência'), (10, 'Investimentos para Aposentadoria'), (10, 'Investimentos de Curto Prazo'),
    (11, 'Quitação de Empréstimos (Principal)'), (11, 'Juros e Multas (Dívidas)'),
    (12, 'Pós-graduação, Intercâmbio'),
    -- Despesas Discricionárias
    (13, 'Restaurantes, Bares e Delivery'), (13, 'Passeios e Eventos Culturais'), (13, 'Viagens e Hospedagem'),
    (14, 'Streaming (Netflix, Spotify, etc.)'), (14, 'Softwares / Apps Pagos'), (14, 'Academia / Clube'),
    (15, 'Salão de Beleza / Barbearia'), (15, 'Cosméticos e Higiene (não básica)'),
    (16, 'Roupas, Calçados e Acessórios'), (16, 'Eletrônicos e Gadgets'), (16, 'Presentes (Aniversários, Datas)');

    -- 2.4. Inserção da Subcategoria "Outros" (Apenas nas macros Gerais)
    INSERT INTO SubCategoria (macro_id, nome_sub) VALUES
    (17, 'Outros'), -- Ligado à 'Despesas Gerais'
    (18, 'Outros'); -- Ligado à 'Receitas Gerais'

    COMMIT;
    """)
    
    try:
        with engine.connect() as conn:
            conn.execute(sql_populate_dml) 
            conn.commit()
        return "Dados iniciais (Usuário, Contas, Categorias Normalizadas) inseridos com sucesso!", 200
    except Exception as e:
        # Rollback implícito pelo 'with' em caso de erro
        return f"Erro ao inserir dados: {e}", 500


@app.route('/admin/list-models')
def list_available_models():
    return "Rota de depuração desativada.", 200


# ========= 3. ENDPOINTS PRINCIPAIS (AGORA SALVANDO COM SUBCATEGORIA) =========

@app.route('/')
def home():
    return "API do Bot Financeiro v6 (Categorias Normalizadas) está no ar!"

@app.route('/webhook-automate', methods=['POST'])
def handle_automate_webhook():
    if not engine or not model:
        return jsonify({"status": "erro", "mensagem": "Serviço não configurado"}), 500

    try:
        data = request.json
        texto_notificacao = data.get('texto')
        if not texto_notificacao: return jsonify({"status": "erro", "mensagem": "Chave 'texto' faltando"}), 400
        print(f"[AUTOMATE] Recebido: {texto_notificacao}")

        # 1. CHAMANDO O GEMINI
        prompt_para_gemini = f"""
        Analise a notificação: "{texto_notificacao}"
        Retorne APENAS JSON com: "valor_decimal", "descricao_bruta", "tipo_fluxo" ("RECEITA" ou "DESPESA").
        Ex: {{"valor_decimal": 45.00, "descricao_bruta": "PADARIA", "tipo_fluxo": "DESPESA"}}
        """
        response = model.generate_content(prompt_para_gemini)
        json_response_text = response.text.strip().replace("```json", "").replace("```", "")
        transacao_gemini = json.loads(json_response_text)
        print(f"[GEMINI] Resposta: {json_response_text}")

        # 2. DECISÃO DE CATEGORIA E CONTA (SIMPLIFICADA)
        id_conta_fixa = 1   # ID da conta 'Banco Inter' (Primeira conta criada)
        
        # Encontra o ID da SubCategoria "Outros" apropriada (Receita ou Despesa)
        # Assumindo que a Macro "Receitas Gerais" é ID 18 e "Despesas Gerais" é ID 17
        id_macro_geral = 18 if transacao_gemini['tipo_fluxo'] == 'RECEITA' else 17
        
        # Precisamos buscar o ID da subcategoria "Outros" dentro dessa macro
        sql_find_subcat = text("SELECT id FROM SubCategoria WHERE macro_id = :macro_id AND nome_sub = 'Outros'")
        id_subcategoria_outros = None
        with engine.connect() as conn:
            result = conn.execute(sql_find_subcat, {"macro_id": id_macro_geral})
            id_subcategoria_outros = result.scalar_one_or_none()

        if id_subcategoria_outros is None:
             print(f"ERRO CRÍTICO: Não foi possível encontrar a SubCategoria 'Outros' para a Macro ID {id_macro_geral}")
             # Poderia usar um ID fixo de fallback aqui ou retornar erro
             id_subcategoria_outros = 1 # Fallback MUITO arriscado, apenas para não quebrar agora

        # 3. SALVANDO NO BANCO DE DADOS
        sql_insert = text("""
        INSERT INTO Transacoes (id_conta, id_subcategoria, descricao, valor, tipo)
        VALUES (:id_conta, :id_subcategoria, :descricao, :valor, :tipo) 
        """) # Não precisa mais do CAST ::tipo_fluxo pois tipo agora é VARCHAR(10)
        
        with engine.connect() as conn:
            conn.execute(sql_insert, {
                "id_conta": id_conta_fixa, 
                "id_subcategoria": id_subcategoria_outros, 
                "descricao": transacao_gemini['descricao_bruta'],
                "valor": transacao_gemini['valor_decimal'],
                "tipo": transacao_gemini['tipo_fluxo'] 
            })
            conn.commit()
        
        print(f"[DATABASE] Transação salva com sucesso na conta {id_conta_fixa}!")

        return jsonify({"status": "sucesso", "transacao_salva": transacao_gemini}), 200

    except Exception as e:
        print(f"Erro no webhook do Automate: {e}")
        return jsonify({"status": "erro", "mensagem": str(e)}), 500

@app.route('/webhook-whatsapp', methods=['POST'])
def handle_whatsapp_webhook():
    return jsonify({"status": "Ainda não implementado"}), 200