import os
import json
from flask import Flask, request, jsonify
import google.generativeai as genai
from sqlalchemy import create_engine, text, exc as sqlalchemy_exc # Importa exceções do SQLAlchemy

# ========= 1. CONFIGURAÇÃO INICIAL E CONEXÃO =========

app = Flask(__name__)

# Carregar as "senhas"
try:
    GEMINI_API_KEY = os.environ['GEMINI_API_KEY']
    DATABASE_URL = os.environ['DATABASE_URL']
except KeyError:
    GEMINI_API_KEY = None
    DATABASE_URL = None

# Configurar o cliente do Gemini
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel('models/gemini-flash-latest') 
else:
    model = None

# Configurar a conexão com o Banco de Dados
if DATABASE_URL:
    if DATABASE_URL.startswith("postgres://"):
        DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
    engine = create_engine(DATABASE_URL)
else:
    engine = None


# ========= 2. ROTAS ADMINISTRATIVAS =========

@app.route('/admin/setup-database', methods=['GET'])
def setup_database():
    """
    Cria/Recria a ESTRUTURA completa do banco com o novo schema normalizado.
    Execute PRIMEIRO.
    """
    if not engine:
        return "Erro: Conexão com o banco de dados não configurada.", 500

    # SEU NOVO SCRIPT DDL (Parte 1)
    sql_script_ddl = """
    DROP TABLE IF EXISTS Transacoes CASCADE;
    DROP TABLE IF EXISTS Contas CASCADE;
    DROP TABLE IF EXISTS SubCategoria CASCADE;
    DROP TABLE IF EXISTS MacroCategoria CASCADE;
    DROP TABLE IF EXISTS GrupoCategoria CASCADE;
    DROP TABLE IF EXISTS Usuarios CASCADE;

    CREATE TABLE Usuarios (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(255) NOT NULL,
        numero_whatsapp VARCHAR(50) NOT NULL UNIQUE,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE GrupoCategoria (
        id SERIAL PRIMARY KEY,
        nome_grupo VARCHAR(100) NOT NULL UNIQUE
    );

    CREATE TABLE MacroCategoria (
        id SERIAL PRIMARY KEY,
        grupo_id INT NOT NULL REFERENCES GrupoCategoria(id) ON DELETE RESTRICT,
        usuario_id INT REFERENCES Usuarios(id) ON DELETE CASCADE, -- NULL para global
        nome_macro VARCHAR(255) NOT NULL,
        ordem_macro INT
    );

    CREATE TABLE SubCategoria (
        id SERIAL PRIMARY KEY,
        macro_id INT NOT NULL REFERENCES MacroCategoria(id) ON DELETE CASCADE,
        usuario_id INT REFERENCES Usuarios(id) ON DELETE CASCADE, -- NULL para global
        nome_sub VARCHAR(255) NOT NULL,
        UNIQUE(macro_id, nome_sub, usuario_id) -- Evita duplicatas por usuário ou global
    );

    CREATE TABLE Contas (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
        nome_conta VARCHAR(100) NOT NULL,
        tipo_conta VARCHAR(50) CHECK (tipo_conta IN ('Conta Corrente', 'Conta Poupança', 'Investimento', 'Cartão de Crédito', 'Dinheiro', 'Outro')),
        saldo_inicial NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
         UNIQUE(usuario_id, nome_conta) -- Evita contas duplicadas para o mesmo usuário
    );

    CREATE TABLE Transacoes (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        usuario_id INT NOT NULL REFERENCES Usuarios(id) ON DELETE CASCADE,
        conta_id INT NOT NULL REFERENCES Contas(id) ON DELETE RESTRICT,
        subcategoria_id INT REFERENCES SubCategoria(id) ON DELETE RESTRICT, -- Alterado para não permitir nulo inicialmente
        descricao VARCHAR(255) NOT NULL,
        valor NUMERIC(15, 2) NOT NULL CHECK (valor >= 0), -- Permite valor zero para transferências? Ou deve ser > 0?
        data_transacao DATE NOT NULL DEFAULT CURRENT_DATE,
        tipo_transacao VARCHAR(10) NOT NULL CHECK (tipo_transacao IN ('Renda', 'Despesa', 'Transferência')),
        consolidada BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    -- Índices
    CREATE INDEX IF NOT EXISTS idx_macro_grupo_id ON MacroCategoria(grupo_id);
    CREATE INDEX IF NOT EXISTS idx_sub_macro_id ON SubCategoria(macro_id);
    CREATE INDEX IF NOT EXISTS idx_macro_usuario_id ON MacroCategoria(usuario_id);
    CREATE INDEX IF NOT EXISTS idx_sub_usuario_id ON SubCategoria(usuario_id);
    CREATE INDEX IF NOT EXISTS idx_contas_usuario_id ON Contas(usuario_id);
    CREATE INDEX IF NOT EXISTS idx_transacoes_usuario_id ON Transacoes(usuario_id);
    CREATE INDEX IF NOT EXISTS idx_transacoes_conta_id ON Transacoes(conta_id);
    CREATE INDEX IF NOT EXISTS idx_transacoes_subcategoria_id ON Transacoes(subcategoria_id);
    """
    
    try:
        with engine.connect() as conn:
            conn.execute(text(sql_script_ddl))
            conn.commit() 
        return "Estrutura normalizada do banco criada/recriada com sucesso!", 200
    except Exception as e:
        # Tenta reverter em caso de erro parcial
        try: 
            with engine.connect() as conn: conn.rollback()
        except: pass # Ignora erros no rollback
        return f"Erro ao criar estrutura do banco: {e}", 500


@app.route('/admin/populate-global-categories', methods=['GET'])
def populate_global_categories():
    """
    Insere os TEMPLATES GLOBAIS de categorias (usuario_id = NULL).
    Execute SEGUNDO, após /admin/setup-database.
    """
    if not engine:
        return "Erro: Conexão com o banco de dados não configurada.", 500

    # SEU NOVO SCRIPT DML (Parte 2 - Templates Globais)
    # Adicionei a Macro 'Despesas Gerais' e 'Receitas Gerais' para o 'Outros'
    sql_populate_dml = text("""
    BEGIN;

    -- Limpa apenas os templates globais antes de inserir
    DELETE FROM SubCategoria WHERE usuario_id IS NULL;
    DELETE FROM MacroCategoria WHERE usuario_id IS NULL;
    DELETE FROM GrupoCategoria; -- Grupos são sempre globais

    -- 2.1. Inserir os Grupos Globais
    INSERT INTO GrupoCategoria (nome_grupo) VALUES
    ('Renda'), ('Despesa Essencial'), ('Meta Financeira'), ('Despesa Discricionária'), ('Geral');

    -- 2.2. Inserir as Macro Categorias GLOBAIS (usuario_id fica NULL)
    INSERT INTO MacroCategoria (grupo_id, nome_macro, ordem_macro) VALUES
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Renda'), 'Renda Principal', 1),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Renda'), 'Renda Extra e Passiva', 2),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Renda'), 'Investimentos e Reembolsos', 3),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Renda'), 'Outras Entradas', 4),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Moradia e Contas', 1),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Alimentação Essencial', 2),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Saúde e Bem-Estar Básico', 3),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Educação Essencial', 4),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Essencial'), 'Transporte Essencial', 5),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Meta Financeira'), 'Construção de Riqueza', 1),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Meta Financeira'), 'Gerenciamento de Dívidas', 2),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Meta Financeira'), 'Educação de Alto Custo', 3),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Discricionária'), 'Lazer e Entretenimento', 1),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Discricionária'), 'Assinaturas e Serviços', 2),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Discricionária'), 'Cuidados Pessoais', 3),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Despesa Discricionária'), 'Compras Pessoais', 4),
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Geral'), 'Despesas Gerais', NULL), -- Para Despesas 'Outros'
    ((SELECT id FROM GrupoCategoria WHERE nome_grupo = 'Geral'), 'Receitas Gerais', NULL); -- Para Receitas 'Outros'

    -- 2.3. Inserir as Sub Categorias GLOBAIS (usuario_id fica NULL)
    -- (O script aqui é idêntico ao que você forneceu, apenas garantindo usuario_id IS NULL nos SELECTs)
    INSERT INTO SubCategoria (macro_id, nome_sub) VALUES
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Principal' AND usuario_id IS NULL), 'Salário Fixo / Pró-labore'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Principal' AND usuario_id IS NULL), 'Remuneração Variável / Comissões'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Extra e Passiva' AND usuario_id IS NULL), 'Aluguéis Recebidos'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Extra e Passiva' AND usuario_id IS NULL), 'Freelances / Projetos Avulsos'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Investimentos e Reembolsos' AND usuario_id IS NULL), 'Dividendos / Juros (Rendimentos)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Investimentos e Reembolsos' AND usuario_id IS NULL), 'Restituições / Reembolsos'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Outras Entradas' AND usuario_id IS NULL), 'Presentes em Dinheiro / Doações'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Outras Entradas' AND usuario_id IS NULL), 'Venda de Bens (Pontual)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Aluguel / Financiamento'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Condomínio / IPTU / Taxas'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Eletricidade / Água / Gás'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Internet / Telefone Fixo'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Manutenção da Casa'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Alimentação Essencial' AND usuario_id IS NULL), 'Supermercado / Mercearia'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Alimentação Essencial' AND usuario_id IS NULL), 'Feira / Hortifrúti'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Alimentação Essencial' AND usuario_id IS NULL), 'Suplementos e Itens Básicos'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Saúde e Bem-Estar Básico' AND usuario_id IS NULL), 'Plano de Saúde / Convênio'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Saúde e Bem-Estar Básico' AND usuario_id IS NULL), 'Medicamentos de Uso Contínuo'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Saúde e Bem-Estar Básico' AND usuario_id IS NULL), 'Consultas e Exames (não cobertos)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Educação Essencial' AND usuario_id IS NULL), 'Mensalidades Escolares / Faculdade'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Educação Essencial' AND usuario_id IS NULL), 'Material Didático e Livros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Transporte Essencial' AND usuario_id IS NULL), 'Combustível / Recarga (Carro/Moto)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Transporte Essencial' AND usuario_id IS NULL), 'Transporte Público (Bilhetes/Passe)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Transporte Essencial' AND usuario_id IS NULL), 'Aplicativos de Transporte (Necessidade)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Transporte Essencial' AND usuario_id IS NULL), 'IPVA / Seguro do Veículo'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Construção de Riqueza' AND usuario_id IS NULL), 'Aporte à Reserva de Emergência'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Construção de Riqueza' AND usuario_id IS NULL), 'Investimentos para Aposentadoria'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Construção de Riqueza' AND usuario_id IS NULL), 'Investimentos de Curto Prazo'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Gerenciamento de Dívidas' AND usuario_id IS NULL), 'Quitação de Empréstimos (Principal)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Gerenciamento de Dívidas' AND usuario_id IS NULL), 'Juros e Multas (Dívidas)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Educação de Alto Custo' AND usuario_id IS NULL), 'Pós-graduação, Intercâmbio'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Lazer e Entretenimento' AND usuario_id IS NULL), 'Restaurantes, Bares e Delivery'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Lazer e Entretenimento' AND usuario_id IS NULL), 'Passeios e Eventos Culturais'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Lazer e Entretenimento' AND usuario_id IS NULL), 'Viagens e Hospedagem'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Assinaturas e Serviços' AND usuario_id IS NULL), 'Streaming (Netflix, Spotify, etc.)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Assinaturas e Serviços' AND usuario_id IS NULL), 'Softwares / Apps Pagos'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Assinaturas e Serviços' AND usuario_id IS NULL), 'Academia / Clube'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Cuidados Pessoais' AND usuario_id IS NULL), 'Salão de Beleza / Barbearia'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Cuidados Pessoais' AND usuario_id IS NULL), 'Cosméticos e Higiene (não básica)'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Compras Pessoais' AND usuario_id IS NULL), 'Roupas, Calçados e Acessórios'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Compras Pessoais' AND usuario_id IS NULL), 'Eletrônicos e Gadgets'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Compras Pessoais' AND usuario_id IS NULL), 'Presentes (Aniversários, Datas)');

    -- 2.4. Inserção da Subcategoria "Outros" nas macros GERAIS globais
    INSERT INTO SubCategoria (macro_id, nome_sub) VALUES
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Despesas Gerais' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Receitas Gerais' AND usuario_id IS NULL), 'Outros'),
    -- Adicionando "Outros" em TODAS as outras macros globais também (opcional, mas útil)
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Principal' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Renda Extra e Passiva' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Investimentos e Reembolsos' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Outras Entradas' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Moradia e Contas' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Alimentação Essencial' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Saúde e Bem-Estar Básico' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Educação Essencial' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Transporte Essencial' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Construção de Riqueza' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Gerenciamento de Dívidas' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Educação de Alto Custo' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Lazer e Entretenimento' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Assinaturas e Serviços' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Cuidados Pessoais' AND usuario_id IS NULL), 'Outros'),
    ((SELECT id FROM MacroCategoria WHERE nome_macro = 'Compras Pessoais' AND usuario_id IS NULL), 'Outros');

    COMMIT;
    """)
    
    try:
        with engine.connect() as conn:
            conn.execute(sql_populate_dml) 
            conn.commit()
        return "Templates globais de categorias inseridos com sucesso!", 200
    except Exception as e:
        try: 
            with engine.connect() as conn: conn.rollback()
        except: pass
        return f"Erro ao inserir templates globais: {e}", 500


@app.route('/admin/list-models')
def list_available_models():
    return "Rota de depuração desativada.", 200

# Rota para o usuário inserir seus próprios dados (exemplo simples)
@app.route('/admin/setup-user-data', methods=['GET']) 
def setup_user_data():
    """ Rota para inserir o usuário e suas contas. Execute TERCEIRO. """
    if not engine: return "Erro: Banco não configurado.", 500
    
    numero_whatsapp_usuario = '553194001072' 

    sql_user = text(f"INSERT INTO Usuarios (nome, numero_whatsapp) VALUES ('Rafael', '{numero_whatsapp_usuario}') ON CONFLICT (numero_whatsapp) DO NOTHING RETURNING id;")
    sql_accounts = text("""
        INSERT INTO Contas (usuario_id, nome_conta, tipo_conta) VALUES 
            (1, 'Banco Inter', 'Conta Corrente'),         
            (1, 'Cartão Inter', 'Cartão de Crédito'),    
            (1, 'Nubank', 'Conta Corrente'),             
            (1, 'Carteira', 'Dinheiro')
        ON CONFLICT (usuario_id, nome_conta) DO NOTHING; 
    """)

    try:
        with engine.connect() as conn:
            # Insere usuário ou obtém ID se já existe
            result = conn.execute(sql_user)
            user_id = result.scalar_one_or_none()
            if user_id is None: # Se usuário já existia, busca o ID
                 find_user_sql = text("SELECT id FROM Usuarios WHERE numero_whatsapp = :num")
                 result = conn.execute(find_user_sql, {"num": numero_whatsapp_usuario})
                 user_id = result.scalar_one() # Assume que usuário existe
            
            # Insere contas usando o user_id correto (sempre 1 neste caso)
            # Precisaria ajustar se user_id não fosse 1
            conn.execute(sql_accounts) 
            conn.commit()
        return f"Usuário e Contas inseridos/verificados com sucesso (Usuário ID: {user_id})!", 200
    except Exception as e:
        try: 
            with engine.connect() as conn: conn.rollback()
        except: pass
        return f"Erro ao inserir dados do usuário: {e}", 500


# ========= 3. ENDPOINTS PRINCIPAIS =========

@app.route('/')
def home():
    return "API do Bot Financeiro v7 (Schema Final) está no ar!"

@app.route('/webhook-automate', methods=['POST'])
def handle_automate_webhook():
    if not engine or not model:
        return jsonify({"status": "erro", "mensagem": "Serviço não configurado"}), 500

    try:
        data = request.json
        texto_notificacao = data.get('texto')
        if not texto_notificacao: return jsonify({"status": "erro", "mensagem": "Chave 'texto' faltando"}), 400
        print(f"[AUTOMATE] Recebido: {texto_notificacao}")

        # 1. CHAMANDO O GEMINI (para extrair e classificar Renda/Despesa)
        prompt_para_gemini = f"""
        Analise a notificação: "{texto_notificacao}"
        Retorne APENAS JSON com: "valor_decimal", "descricao_bruta", "tipo_fluxo" ("Renda" ou "Despesa").
        Ex: {{"valor_decimal": 45.00, "descricao_bruta": "PADARIA", "tipo_fluxo": "Despesa"}}
        """
        response = model.generate_content(prompt_para_gemini)
        json_response_text = response.text.strip().replace("```json", "").replace("```", "")
        transacao_gemini = json.loads(json_response_text)
        print(f"[GEMINI] Resposta: {json_response_text}")
        
        # Mapeia tipo_fluxo para tipo_transacao do banco ('Renda'/'Despesa')
        tipo_transacao_db = transacao_gemini.get('tipo_fluxo', 'Despesa') # Default para Despesa

        # 2. IDENTIFICAÇÃO (SIMPLIFICADA)
        usuario_id_fixo = 1 # Assumindo que você é sempre o usuário 1
        conta_id_fixa = 1   # Assumindo conta 'Banco Inter' (precisaria de lógica para identificar a conta)
        
        # 3. ENCONTRAR SUBCATEGORIA "OUTROS" APROPRIADA
        nome_macro_outros = 'Receitas Gerais' if tipo_transacao_db == 'Renda' else 'Despesas Gerais'
        
        sql_find_subcat_outros = text("""
            SELECT s.id 
            FROM SubCategoria s
            JOIN MacroCategoria m ON s.macro_id = m.id
            WHERE m.nome_macro = :nome_macro 
              AND s.nome_sub = 'Outros' 
              AND s.usuario_id IS NULL -- Busca o template global
            LIMIT 1
        """)
        id_subcategoria_outros = None
        with engine.connect() as conn:
            result = conn.execute(sql_find_subcat_outros, {"nome_macro": nome_macro_outros})
            id_subcategoria_outros = result.scalar_one_or_none()

        if id_subcategoria_outros is None:
             print(f"ERRO CRÍTICO: Não foi possível encontrar a SubCategoria global 'Outros' para a Macro '{nome_macro_outros}'")
             return jsonify({"status": "erro", "mensagem": "Erro interno: Categoria 'Outros' não encontrada"}), 500

        # 4. SALVANDO NO BANCO DE DADOS
        sql_insert = text("""
        INSERT INTO Transacoes (usuario_id, conta_id, subcategoria_id, descricao, valor, tipo_transacao, data_transacao)
        VALUES (:uid, :cid, :scid, :desc, :val, :tipo, CURRENT_DATE) 
        """) 
        
        with engine.connect() as conn:
            conn.execute(sql_insert, {
                "uid": usuario_id_fixo,
                "cid": conta_id_fixa, 
                "scid": id_subcategoria_outros, 
                "desc": transacao_gemini['descricao_bruta'],
                "val": transacao_gemini['valor_decimal'],
                "tipo": tipo_transacao_db 
            })
            conn.commit()
        
        print(f"[DATABASE] Transação salva com sucesso (Usuário: {usuario_id_fixo}, Conta: {conta_id_fixa}, SubCat: {id_subcategoria_outros})!")

        return jsonify({"status": "sucesso", "transacao_salva": transacao_gemini}), 200

    # Captura erros específicos do banco de dados também
    except sqlalchemy_exc.SQLAlchemyError as db_err:
        print(f"Erro de Banco de Dados no webhook do Automate: {db_err}")
        return jsonify({"status": "erro", "mensagem": f"Erro de Banco de Dados: {db_err}"}), 500
    except Exception as e:
        print(f"Erro geral no webhook do Automate: {e}")
        return jsonify({"status": "erro", "mensagem": str(e)}), 500


@app.route('/webhook-whatsapp', methods=['POST'])
def handle_whatsapp_webhook():
    # Aqui precisaremos implementar a lógica para:
    # 1. Verificar se o número remetente está na tabela Usuarios.
    # 2. Chamar o Gemini para extrair dados da mensagem do usuário.
    # 3. Determinar conta_id e subcategoria_id (talvez perguntando ao usuário?).
    # 4. Salvar na tabela Transacoes.
    # 5. Enviar resposta de confirmação.
    return jsonify({"status": "Ainda não implementado"}), 200